### ISSUE TITLE
Strange convention for coordinate frames

### ISSUE THREAD

**Issue by yifanzhu95** [EmbodiedVision/diffsdfsim#2]
Hi,

I find that the DOWN direction is -y (same as gravity). This is an interesting choice. Why is it designed that way? Thanks!

**Comment by streckus** [comment]
Hi, there's no particular reason for this choice. In the [2D LCP physics engine](https://github.com/locuslab/lcp-physics), the Y-axis was pointing upwards and we kept it that way.
